/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_andr0day_soencrypt_MainActivity */

#ifndef _Included_com_andr0day_soencrypt_MainActivity
#define _Included_com_andr0day_soencrypt_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_andr0day_soencrypt_MainActivity
 * Method:    getStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_andr0day_soencrypt_MainActivity_getStr
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
